export const HANDLE_CHANGE="HANDLE_CHANGE"

export const HANDLE_CHECK="HANDLE_CHECK"

export const QUIZ_START="QUIZ_START"

export const INCREASE_QUESTION_INDEX="INCREASE_QUESTION_INDEX"
export const INCREASE_CORRECT_ANSWERS="INCREASE_CORRECT_ANSWERS"


export const SELECTED_OPTION="SELECTED_OPTION"

export const DATA="DATA"

export const MODEL="MODEL"


export const RESET='Reset'